# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=250, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
    ]
